Translate implement/implementing into ja
goadesign/goa.design pull request #128
Opened 2021-12-10 01:33 UTC by ikawaha

2021-12-10 01:34 UTC, ikawaha commented on content/implement/implementing.ja.md
> +エンドポイント階層は、共通のGoの関数のシグネチャを用いて各サービスを表現し、すべてのメソッドに適用される直交動作の実装（トランスポートに依存しないミドルウエアともいえるでしょう）を可能にします。
ここ、よく理解できなかったです・・・

2021-12-10 01:35 UTC, ikawaha commented on content/implement/implementing.ja.md
> +そのほかのエラーは [ServiceError](https://pkg.go.dev/goa.design/goa/v3/pkg#ServiceError) 構造体を使ってフォーマットされます。
ここ、よく理解できなかったです・・・

2021-12-10 01:48 UTC, raphael commented
This is great! thank you for fixing the typos. Looks like the GitHub action is not quite right (should not try to deploy on a commit, only when merging) - I'll look into it.

2021-12-11 20:20 UTC, raphael commented
> This is great! thank you for fixing the typos. Looks like the GitHub action is not quite right (should not try to deploy on a commit, only when merging) - I'll look into it.

This is now fixed - the "Publish" action will only run after a PR has been merged.

2021-12-12 15:33 UTC, tchssk commented on content/implement/implementing.ja.md
> +各サービスごとに Goa はトランスポート階層、エンドポイント階層、そしてサービス層を生成します。
> サービス層

`layer` を `階層` とするならこれも `サービス階層` とすべきだと思いますが、
`layer` を `層` に統一しても良いかもしれません。

2021-12-20 10:59 UTC, tchssk commented on content/implement/implementing.ja.md
> +構造体のフィールドはパブリックなので、ユーザーコードでどのエンドポイントもオーバーラードすることができます：
s/オーバーラード/オーバーライド/

2021-12-20 10:59 UTC, tchssk commented on content/implement/implementing.ja.md
> +サーバを作成する `New` 関数は、エンドポイント固有の公開された関数に単にデリゲートします。この関数はパブリックであり、個別に呼び出すことができます。
s/オーバーラード/オーバーライド/

2021-12-20 10:59 UTC, tchssk commented on content/implement/implementing.ja.md
> +そのほかのエラーは [ServiceError](https://pkg.go.dev/goa.design/goa/v3/pkg#ServiceError) 構造体を使ってフォーマットされます。
s/オーバーラード/オーバーライド/

2021-12-20 10:59 UTC, tchssk commented on content/implement/implementing.ja.md
> +mux オブジェクトは標準的な Go の HTTP ハンドラーで、HTTP リクエストを扱うために利用できます：
ハンドラとハンドラーで表記ゆれがあるようです。
ただ、翻訳済みの文書にも同様の問題があるようなので後で一括で対応してもいいかもしれません。

2021-12-20 11:26 UTC, ikawaha commented on content/implement/implementing.ja.md
> +構造体のフィールドはパブリックなので、ユーザーコードでどのエンドポイントもオーバーラードすることができます：
油取り過ぎ・・・ 
927ae3e  で修正しました

2021-12-20 11:27 UTC, ikawaha commented on content/implement/implementing.ja.md
> +サーバを作成する `New` 関数は、エンドポイント固有の公開された関数に単にデリゲートします。この関数はパブリックであり、個別に呼び出すことができます。
927ae3e で修正しました

2021-12-20 11:27 UTC, ikawaha commented on content/implement/implementing.ja.md
> +そのほかのエラーは [ServiceError](https://pkg.go.dev/goa.design/goa/v3/pkg#ServiceError) 構造体を使ってフォーマットされます。
927ae3e で修正しました

2021-12-20 11:27 UTC, ikawaha commented on content/implement/implementing.ja.md
> +mux オブジェクトは標準的な Go の HTTP ハンドラーで、HTTP リクエストを扱うために利用できます：
全体的にハンドラが多そうだったので、この文書ではハンドラで統一しました。
あとで他の部分を合わせようと思います。

2022-01-07 11:35 UTC, ikawaha commented
ping @tchssk

2022-01-07 14:09 UTC, tchssk commented on content/implement/implementing.ja.md
> +最後に、サービス階層はビジネスロジックのある階層です。Goa は各サービスのインターフェースを生成し、ユーザーはそれらの実装して提供します。
`ユーザーはそれらの実装を用意します。` がより適切でしょうか？

2022-01-09 12:17 UTC, ikawaha commented on content/implement/implementing.ja.md
> +最後に、サービス階層はビジネスロジックのある階層です。Goa は各サービスのインターフェースを生成し、ユーザーはそれらの実装して提供します。
修正しました fd82dfd

2022-01-09 14:21 UTC, tchssk requested changes

2022-01-09 14:21 UTC, tchssk commented on content/implement/implementing.ja.md
> +最後に、サービス階層はビジネスロジックのある階層です。Goa は各サービスのインターフェースを生成し、ユーザーはそれらの実装を用意します
```suggestion
最後に、サービス階層はビジネスロジックのある階層です。Goa は各サービスのインターフェースを生成し、ユーザーはそれらの実装を用意します。
```

2022-01-09 15:26 UTC, tchssk approved these changes

2022-01-12 02:54 UTC, ikawaha commented
@raphael Japanese review completed. Please merge.

This PR includes the followings:
* Add Japanese translations, and
* Fix typo (493c184).

Thank you.

2022-01-12 04:24 UTC, raphael commented
This is awesome, thank you!

2022-01-12 04:25 UTC, merged

2022-01-12 04:45 UTC, raphael commented
The change is live! I noticed that the menu title doesn't seem to be translated though:
![image](https://user-images.githubusercontent.com/36822/149065318-de8f9a0d-d4f3-4839-8602-8d9ad0ba62c6.png)